# Generated by Django 5.0.6 on 2024-07-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient_list',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes_api.recipe'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes_api.recipe'),
        ),
    ]
