# Generated by Django 5.0.6 on 2024-07-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0002_ingredient_list_recipe_alter_instruction_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.CreateModel(
            name='Instruction_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes_api.instruction')),
                ('recipe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes_api.recipe')),
            ],
        ),
    ]
