# Generated by Django 5.0.6 on 2024-07-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0003_remove_instruction_recipe_instruction_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction_list',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes_api.recipe'),
        ),
    ]
