# Generated by Django 5.0.6 on 2024-07-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0004_alter_instruction_list_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_list',
            old_name='ingredients',
            new_name='ingredients_list',
        ),
        migrations.RenameField(
            model_name='instruction_list',
            old_name='instructions',
            new_name='instructions_list',
        ),
        migrations.RemoveField(
            model_name='ingredient_list',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='instruction_list',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes_api.ingredient_list'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes_api.instruction_list'),
        ),
    ]
