# Generated by Django 5.0.6 on 2024-07-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0005_rename_ingredients_ingredient_list_ingredients_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_list',
            old_name='ingredients_list',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='instruction_list',
            old_name='instructions_list',
            new_name='instructions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='recipes_api.ingredient_list'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions_list', to='recipes_api.instruction_list'),
        ),
    ]
