# Generated by Django 5.0.6 on 2024-07-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0008_remove_instruction_list_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='list',
        ),
        migrations.AddField(
            model_name='instruction_list',
            name='instructions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes_api.instruction'),
        ),
    ]
