# Generated by Django 5.0.6 on 2024-07-12 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0011_alter_ingredient_list_recipe_alter_instruction_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('measurement', models.CharField(max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_api.ingredient')),
                ('ingredient_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_entries', to='recipes_api.ingredient_list')),
            ],
        ),
    ]
