# Generated by Django 5.0.6 on 2024-07-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0012_ingredientlistentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='type',
        ),
    ]
