# Generated by Django 5.0.6 on 2024-07-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0015_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(default='cup', max_length=15),
            preserve_default=False,
        ),
    ]
