# Generated by Django 5.0.6 on 2024-07-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0016_ingredient_amount_ingredient_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement',
        ),
    ]
