# Generated by Django 5.0.6 on 2024-07-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0017_remove_ingredient_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_ref',
            field=models.CharField(max_length=250),
        ),
    ]
